CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT,
  language VARCHAR DEFAULT 'fr',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid TEXT UNIQUE NOT NULL,
  game_name TEXT NOT NULL,
  player1 TEXT NOT NULL,
  player2 TEXT,
  player3 TEXT,
  player4 TEXT,
  users_needed INTEGER,
  ai INTEGER DEFAULT 0,
  start_time TEXT,
  end_time TEXT,
  winner TEXT
);

CREATE TABLE IF NOT EXISTS chats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type VARCHAR NOT NULL,
  name VARCHAR,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_1 INTEGER REFERENCES users(id),
  user_2 INTEGER REFERENCES users(id),
  user1_state VARCHAR(36) NOT NULL,
  user2_state VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,
  sender_id INTEGER REFERENCES users(id),
  content TEXT NOT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS statistics (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  mmr INTEGER DEFAULT 800,
  pong_games INTEGER DEFAULT 0,
  pong_wins INTEGER DEFAULT 0,
  block_games INTEGER DEFAULT 0,
  block_wins INTEGER DEFAULT 0,
  rating INTEGER
)

-- CREATE TABLE IF NOT EXISTS tournaments (
--   tournaments_id INTEGER PRIMARY KEY AUTOINCREMENT,
--   player_ids TEXT NOT NULL,
--   state INTEGER DEFAULT 0
-- )
