CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR UNIQUE NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT,
  language VARCHAR DEFAULT 'fr',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_name TEXT NOT NULL,
  player1 TEXT NOT NULL,
  player2 TEXT,
  player3 TEXT,
  player4 TEXT,
  winner TEXT,
  start_time TEXT,
  end_time TEXT
);

CREATE TABLE IF NOT EXISTS chats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type VARCHAR NOT NULL,
  name VARCHAR,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_1 INTEGER REFERENCES users(id),
  user_2 INTEGER REFERENCES users(id),
  user1_state VARCHAR(36),
  user2_state VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,
  sender_id INTEGER REFERENCES users(id),
  content TEXT NOT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP
);








-- CREATE TABLE IF NOT EXISTS barTables (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   user_tab ARRAY,
--   drinks_tab ARRAY REFERENCES drinks(drink_name),
--   total_cost INTEGER
-- );


-- CREATE TABLE IF NOT EXISTS drinks (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   drink_name  VARCHAR(36) UNIQUE NOT NULL ,
--   cost INTEGER NOT NULL
-- );