apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://nginx:2443/prometheus/
    isDefault: true
    editable: true 
    jsonData:
      tlsSkipVerify: true